-- =====================================================================
-- ANALYTICS TABLES — business-ready star schema
-- (matches your dimensional ER diagram: two fact tables + conformed
-- dimensions + a Julian date dimension)
-- =====================================================================

USE DATABASE HEALTHCARE_DB;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE ANALYTICS.MEDICATION_DIM (
    MEDICATION_ID    NUMBER(38,0) NOT NULL,
    MEDICATION_NAME  VARCHAR(200),
    PHARMA_COMPANY   VARCHAR(200),
    CATEGORY         VARCHAR(100),
    CONSTRAINT PK_MEDICATION_DIM PRIMARY KEY (MEDICATION_ID)
);

CREATE OR REPLACE TABLE ANALYTICS.DOCTOR_DIM (
    DOCTOR_ID          NUMBER(38,0) NOT NULL,
    FIRST_NAME         VARCHAR(100),
    LAST_NAME          VARCHAR(100),
    SPECIALTY          VARCHAR(100),
    DOC_PHONE_NO       VARCHAR(20),
    HOSPITAL_AFFI      VARCHAR(200),
    HOSPITAL_STATE     VARCHAR(100),
    HOSPITAL_CITY      VARCHAR(100),
    HOSPITAL_ZIP       VARCHAR(10),
    HOSPITAL_PHONE_NO  VARCHAR(20),
    CONSTRAINT PK_DOCTOR_DIM PRIMARY KEY (DOCTOR_ID)
);

CREATE OR REPLACE TABLE ANALYTICS.PATIENT_DIM (
    PATIENT_ID            NUMBER(38,0) NOT NULL,
    FIRST_NAME            VARCHAR(100),
    LAST_NAME             VARCHAR(100),
    DOB                   DATE,
    AGE                   NUMBER(3,0),
    AGE_GROUP             VARCHAR(20),
    SEX                   VARCHAR(10),
    PATIENT_PHONE_NO      VARCHAR(20),
    BLOOD_TYPE            VARCHAR(5),
    PRIMARY_INSUR_PROV    VARCHAR(200),
    PRIMARY_PLAN_TYPE     VARCHAR(100),
    SECONDARY_INSUR_PROV  VARCHAR(200),
    SECONDARY_PLAN_TYPE   VARCHAR(100),
    CONSTRAINT PK_PATIENT_DIM PRIMARY KEY (PATIENT_ID)
);

CREATE OR REPLACE TABLE ANALYTICS.PROCEDURE_DIM (
    PROCEDURE_ID      NUMBER(38,0) NOT NULL,
    PROCEDURE_NAME    VARCHAR(200),
    MEDICAL_CATEGORY  VARCHAR(100),
    CONSTRAINT PK_PROCEDURE_DIM PRIMARY KEY (PROCEDURE_ID)
);

CREATE OR REPLACE TABLE ANALYTICS.JULIAN_DATE_DIM (
    JULIAN_DAY    NUMBER(38,0) NOT NULL,  -- YYYYMMDD surrogate key
    ACTUAL_DT     DATE,
    DAY_NAME      VARCHAR(20),
    DAY_ABBREV    VARCHAR(5),
    DAY_IN_YEAR   NUMBER(3,0),
    DAY_IN_MONTH  NUMBER(2,0),
    DAY_IN_WEEK   NUMBER(1,0),
    MONTH_NAME    VARCHAR(20),
    MONTH_ABBREV  VARCHAR(5),
    MONTH_NUM     NUMBER(2,0),
    YEAR_NAME     VARCHAR(10),
    YEAR_NUM      NUMBER(4,0),
    QUARTER       NUMBER(1,0),
    CONSTRAINT PK_JULIAN_DATE_DIM PRIMARY KEY (JULIAN_DAY)
);

CREATE OR REPLACE TABLE ANALYTICS.PRESCRIPTION_FACT (
    PRESCRIPTION_ID  NUMBER(38,0) NOT NULL,
    PATIENT_ID       NUMBER(38,0),
    DOCTOR_ID        NUMBER(38,0),
    MEDICATION_ID    NUMBER(38,0),
    PRESCRIBED_DATE  NUMBER(38,0),
    QUANTITY         NUMBER(10,0),
    DOSAGE           VARCHAR(100),
    FREQUENCY        VARCHAR(100),
    MEDICATION_COST  NUMBER(12,2),
    TOTAL_COST       NUMBER(12,2),
    REFILL_ALLOWED   BOOLEAN,
    REFILL_COUNT     NUMBER(5,0),
    CONSTRAINT PK_PRESCRIPTION_FACT PRIMARY KEY (PRESCRIPTION_ID),
    CONSTRAINT FK_PF_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES ANALYTICS.PATIENT_DIM(PATIENT_ID),
    CONSTRAINT FK_PF_DOCTOR FOREIGN KEY (DOCTOR_ID) REFERENCES ANALYTICS.DOCTOR_DIM(DOCTOR_ID),
    CONSTRAINT FK_PF_MEDICATION FOREIGN KEY (MEDICATION_ID) REFERENCES ANALYTICS.MEDICATION_DIM(MEDICATION_ID),
    CONSTRAINT FK_PF_DATE FOREIGN KEY (PRESCRIBED_DATE) REFERENCES ANALYTICS.JULIAN_DATE_DIM(JULIAN_DAY)
);

CREATE OR REPLACE TABLE ANALYTICS.HOSPITAL_VISIT_FACT (
    VISIT_ID             NUMBER(38,0) NOT NULL,
    ADMISSION_DATE       NUMBER(38,0),
    DISCHARGE_DATE       NUMBER(38,0),
    PATIENT_ID           NUMBER(38,0),
    DOCTOR_ID            NUMBER(38,0),
    HOSPITAL             VARCHAR(200),
    INSURANCE_PROVIDER   VARCHAR(200),
    ROOM_NO              VARCHAR(20),
    ADMISSION_TYPE       VARCHAR(50),
    DIAGNOSIS            VARCHAR(500),
    PROCEDURE_ID         NUMBER(38,0),
    PROCEDURE_CHARGE     NUMBER(12,2),
    ROOM_CHARGE          NUMBER(12,2),
    MISC_CHARGE          NUMBER(12,2),
    BILLING_AMOUNT       NUMBER(12,2),
    LENGTH_OF_STAY       NUMBER(5,0),
    CONSTRAINT PK_HOSPITAL_VISIT_FACT PRIMARY KEY (VISIT_ID),
    CONSTRAINT FK_HVF_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES ANALYTICS.PATIENT_DIM(PATIENT_ID),
    CONSTRAINT FK_HVF_DOCTOR FOREIGN KEY (DOCTOR_ID) REFERENCES ANALYTICS.DOCTOR_DIM(DOCTOR_ID),
    CONSTRAINT FK_HVF_PROCEDURE FOREIGN KEY (PROCEDURE_ID) REFERENCES ANALYTICS.PROCEDURE_DIM(PROCEDURE_ID),
    CONSTRAINT FK_HVF_ADMIT_DATE FOREIGN KEY (ADMISSION_DATE) REFERENCES ANALYTICS.JULIAN_DATE_DIM(JULIAN_DAY),
    CONSTRAINT FK_HVF_DISCHARGE_DATE FOREIGN KEY (DISCHARGE_DATE) REFERENCES ANALYTICS.JULIAN_DATE_DIM(JULIAN_DAY)
);

-- ---------------------------------------------------------------------
-- TRANSFORM: STAGING -> ANALYTICS
-- ---------------------------------------------------------------------

-- Julian date dimension: generate one row per calendar day for a
-- 20-year span. Adjust the date range to fit your actual data.
INSERT OVERWRITE INTO ANALYTICS.JULIAN_DATE_DIM
SELECT
    TO_NUMBER(TO_CHAR(D, 'YYYYMMDD'))      AS JULIAN_DAY,
    D                                       AS ACTUAL_DT,
    DAYNAME(D)                              AS DAY_NAME,
    LEFT(DAYNAME(D), 3)                     AS DAY_ABBREV,
    DAYOFYEAR(D)                             AS DAY_IN_YEAR,
    DAYOFMONTH(D)                            AS DAY_IN_MONTH,
    DAYOFWEEK(D)                             AS DAY_IN_WEEK,
    MONTHNAME(D)                             AS MONTH_NAME,
    LEFT(MONTHNAME(D), 3)                    AS MONTH_ABBREV,
    MONTH(D)                                 AS MONTH_NUM,
    TO_CHAR(YEAR(D))                         AS YEAR_NAME,
    YEAR(D)                                  AS YEAR_NUM,
    QUARTER(D)                               AS QUARTER
FROM (
    SELECT DATEADD(day, SEQ4(), '2010-01-01'::DATE) AS D
    FROM TABLE(GENERATOR(ROWCOUNT => 7305))  -- ~20 years
);

-- MEDICATION_DIM: 1:1 from staging
INSERT OVERWRITE INTO ANALYTICS.MEDICATION_DIM
SELECT MEDICATION_ID, MEDICATION_NAME, PHARMA_COMPANY, CATEGORY
FROM STAGING.MEDICATIONS;

-- PROCEDURE_DIM: 1:1 from staging
INSERT OVERWRITE INTO ANALYTICS.PROCEDURE_DIM
SELECT PROCEDURE_ID, PROCEDURE_NAME, MEDICAL_CATEGORY
FROM STAGING.PROCEDURES;

-- DOCTOR_DIM: denormalize hospital + address chain onto each doctor
INSERT OVERWRITE INTO ANALYTICS.DOCTOR_DIM
SELECT
    doc.DOCTOR_ID,
    doc.FIRST_NAME,
    doc.LAST_NAME,
    doc.SPECIALTY,
    doc.DOC_PHONE_NO,
    hosp.HOSPITAL_NAME       AS HOSPITAL_AFFI,
    st.STATE_NAME             AS HOSPITAL_STATE,
    ci.CITY_NAME               AS HOSPITAL_CITY,
    addr.ZIP                    AS HOSPITAL_ZIP,
    hosp.HOSPITAL_PHONE_NO
FROM STAGING.DOCTORS doc
LEFT JOIN STAGING.HOSPITALS hosp ON doc.HOSPITAL_AFFI = hosp.HOSPITAL_ID
LEFT JOIN STAGING.ADDRESSES addr ON hosp.ADDRESS_ID = addr.ADDRESS_ID
LEFT JOIN STAGING.CITIES ci ON addr.CITY_ID = ci.CITY_ID
LEFT JOIN STAGING.STATES st ON ci.STATE_ID = st.STATE_ID;

-- PATIENT_DIM: compute age/age group, pull primary + secondary insurance
-- (primary/secondary distinguished here by insurance_provider_id order —
-- adjust this logic if your source has an explicit primary/secondary flag)
INSERT OVERWRITE INTO ANALYTICS.PATIENT_DIM
WITH ranked_insurance AS (
    SELECT
        pi.PATIENT_ID,
        ip.PROVIDER_NAME,
        ip.PLAN_TYPE,
        ROW_NUMBER() OVER (PARTITION BY pi.PATIENT_ID ORDER BY ip.INSURANCE_PROVIDER_ID) AS RN
    FROM STAGING.PATIENT_INSURANCE pi
    JOIN STAGING.INSURANCE_PROVIDERS ip ON pi.INSURANCE_PROVIDER_ID = ip.INSURANCE_PROVIDER_ID
)
SELECT
    p.PATIENT_ID,
    p.FIRST_NAME,
    p.LAST_NAME,
    p.DOB,
    DATEDIFF(year, p.DOB, CURRENT_DATE())                                          AS AGE,
    CASE
        WHEN DATEDIFF(year, p.DOB, CURRENT_DATE()) < 18 THEN 'Under 18'
        WHEN DATEDIFF(year, p.DOB, CURRENT_DATE()) BETWEEN 18 AND 34 THEN '18-34'
        WHEN DATEDIFF(year, p.DOB, CURRENT_DATE()) BETWEEN 35 AND 54 THEN '35-54'
        WHEN DATEDIFF(year, p.DOB, CURRENT_DATE()) BETWEEN 55 AND 74 THEN '55-74'
        ELSE '75+'
    END                                                                             AS AGE_GROUP,
    p.SEX,
    NULL                                                                            AS PATIENT_PHONE_NO,  -- not present in source
    p.BLOOD_TYPE,
    pri.PROVIDER_NAME                                                               AS PRIMARY_INSUR_PROV,
    pri.PLAN_TYPE                                                                   AS PRIMARY_PLAN_TYPE,
    sec.PROVIDER_NAME                                                               AS SECONDARY_INSUR_PROV,
    sec.PLAN_TYPE                                                                   AS SECONDARY_PLAN_TYPE
FROM STAGING.PATIENTS p
LEFT JOIN ranked_insurance pri ON p.PATIENT_ID = pri.PATIENT_ID AND pri.RN = 1
LEFT JOIN ranked_insurance sec ON p.PATIENT_ID = sec.PATIENT_ID AND sec.RN = 2;

-- PRESCRIPTION_FACT
INSERT OVERWRITE INTO ANALYTICS.PRESCRIPTION_FACT
SELECT
    rx.PRESCRIPTION_ID,
    rx.PATIENT_ID,
    rx.DOCTOR_ID,
    rx.MEDICATION_ID,
    TO_NUMBER(TO_CHAR(rx.PRESCRIBED_DATE, 'YYYYMMDD'))  AS PRESCRIBED_DATE,
    rx.QUANTITY,
    rx.DOSAGE,
    rx.FREQUENCY,
    m.MEDICATION_COST,
    rx.QUANTITY * m.MEDICATION_COST                     AS TOTAL_COST,
    rx.REFILL_ALLOWED,
    rx.REFILL_COUNT
FROM STAGING.PRESCRIPTIONS rx
LEFT JOIN STAGING.MEDICATIONS m ON rx.MEDICATION_ID = m.MEDICATION_ID;

-- HOSPITAL_VISIT_FACT
INSERT OVERWRITE INTO ANALYTICS.HOSPITAL_VISIT_FACT
SELECT
    hv.VISIT_ID,
    TO_NUMBER(TO_CHAR(hv.ADMISSION_DATE, 'YYYYMMDD'))   AS ADMISSION_DATE,
    TO_NUMBER(TO_CHAR(hv.DISCHARGE_DATE, 'YYYYMMDD'))   AS DISCHARGE_DATE,
    hv.PATIENT_ID,
    hv.DOCTOR_ID,
    hosp.HOSPITAL_NAME                                   AS HOSPITAL,
    ip.PROVIDER_NAME                                      AS INSURANCE_PROVIDER,
    hv.ROOM_NO,
    hv.ADMISSION_TYPE,
    hv.DIAGNOSIS,
    hv.PROCEDURE_ID,
    proc.PROCEDURE_CHARGE,
    NULL                                                    AS ROOM_CHARGE,  -- not present in source; populate if available
    NULL                                                    AS MISC_CHARGE,  -- not present in source; populate if available
    COALESCE(proc.PROCEDURE_CHARGE, 0)                       AS BILLING_AMOUNT,  -- extend once room/misc charges are sourced
    DATEDIFF(day, hv.ADMISSION_DATE, hv.DISCHARGE_DATE)      AS LENGTH_OF_STAY
FROM STAGING.HOSPITAL_VISITS hv
LEFT JOIN STAGING.HOSPITALS hosp ON hv.HOSPITAL_ID = hosp.HOSPITAL_ID
LEFT JOIN STAGING.INSURANCE_PROVIDERS ip ON hv.INSURANCE_PROVIDER_ID = ip.INSURANCE_PROVIDER_ID
LEFT JOIN STAGING.PROCEDURES proc ON hv.PROCEDURE_ID = proc.PROCEDURE_ID;

-- NOTE: ROOM_CHARGE and MISC_CHARGE have no source in your diagrams —
-- BILLING_AMOUNT currently equals PROCEDURE_CHARGE only. If those costs
-- live somewhere else (a billing system, a flat fee schedule), tell me
-- and I'll wire them in.
