-- =====================================================================
-- STAGING TABLES
-- Same grain as RAW, but with proper types, PK/FK constraints declared,
-- and basic cleanup (trimming, standardized casing, deduping) applied
-- on load. This is where you catch bad data before it reaches ANALYTICS.
-- =====================================================================

USE DATABASE HEALTHCARE_DB;
USE SCHEMA STAGING;

CREATE OR REPLACE TABLE STAGING.STATES (
    STATE_ID    NUMBER(38,0) NOT NULL,
    STATE_NAME  VARCHAR(100),
    STATE_ABBR  VARCHAR(2),
    CONSTRAINT PK_STATES PRIMARY KEY (STATE_ID)
);

CREATE OR REPLACE TABLE STAGING.CITIES (
    CITY_ID    NUMBER(38,0) NOT NULL,
    CITY_NAME  VARCHAR(100),
    STATE_ID   NUMBER(38,0),
    CONSTRAINT PK_CITIES PRIMARY KEY (CITY_ID),
    CONSTRAINT FK_CITIES_STATE FOREIGN KEY (STATE_ID) REFERENCES STAGING.STATES(STATE_ID)
);

CREATE OR REPLACE TABLE STAGING.ADDRESSES (
    ADDRESS_ID     NUMBER(38,0) NOT NULL,
    STREET_ADDRESS VARCHAR(200),
    CITY_ID        NUMBER(38,0),
    ZIP            VARCHAR(10),
    CONSTRAINT PK_ADDRESSES PRIMARY KEY (ADDRESS_ID),
    CONSTRAINT FK_ADDRESSES_CITY FOREIGN KEY (CITY_ID) REFERENCES STAGING.CITIES(CITY_ID)
);

CREATE OR REPLACE TABLE STAGING.HOSPITALS (
    HOSPITAL_ID       NUMBER(38,0) NOT NULL,
    HOSPITAL_NAME     VARCHAR(200),
    ADDRESS_ID        NUMBER(38,0),
    HOSPITAL_PHONE_NO VARCHAR(20),
    CONSTRAINT PK_HOSPITALS PRIMARY KEY (HOSPITAL_ID),
    CONSTRAINT FK_HOSPITALS_ADDRESS FOREIGN KEY (ADDRESS_ID) REFERENCES STAGING.ADDRESSES(ADDRESS_ID)
);

CREATE OR REPLACE TABLE STAGING.DOCTORS (
    DOCTOR_ID     NUMBER(38,0) NOT NULL,
    FIRST_NAME    VARCHAR(100),
    LAST_NAME     VARCHAR(100),
    HOSPITAL_AFFI NUMBER(38,0),
    SPECIALTY     VARCHAR(100),
    DOC_PHONE_NO  VARCHAR(20),
    CONSTRAINT PK_DOCTORS PRIMARY KEY (DOCTOR_ID),
    CONSTRAINT FK_DOCTORS_HOSPITAL FOREIGN KEY (HOSPITAL_AFFI) REFERENCES STAGING.HOSPITALS(HOSPITAL_ID)
);

CREATE OR REPLACE TABLE STAGING.MEDICATIONS (
    MEDICATION_ID   NUMBER(38,0) NOT NULL,
    MEDICATION_NAME VARCHAR(200),
    PHARMA_COMPANY  VARCHAR(200),
    CATEGORY        VARCHAR(100),
    MEDICATION_COST NUMBER(12,2),
    CONSTRAINT PK_MEDICATIONS PRIMARY KEY (MEDICATION_ID)
);

CREATE OR REPLACE TABLE STAGING.PROCEDURES (
    PROCEDURE_ID     NUMBER(38,0) NOT NULL,
    PROCEDURE_NAME   VARCHAR(200),
    MEDICAL_CATEGORY VARCHAR(100),
    PROCEDURE_CHARGE NUMBER(12,2),
    CONSTRAINT PK_PROCEDURES PRIMARY KEY (PROCEDURE_ID)
);

CREATE OR REPLACE TABLE STAGING.INSURANCE_PROVIDERS (
    INSURANCE_PROVIDER_ID NUMBER(38,0) NOT NULL,
    PROVIDER_NAME         VARCHAR(200),
    PLAN_TYPE             VARCHAR(100),
    PHONE_NO              VARCHAR(20),
    CONSTRAINT PK_INSURANCE_PROVIDERS PRIMARY KEY (INSURANCE_PROVIDER_ID)
);

CREATE OR REPLACE TABLE STAGING.PATIENTS (
    PATIENT_ID NUMBER(38,0) NOT NULL,
    FIRST_NAME VARCHAR(100),
    LAST_NAME  VARCHAR(100),
    DOB        DATE,
    SEX        VARCHAR(10),
    BLOOD_TYPE VARCHAR(5),
    CONSTRAINT PK_PATIENTS PRIMARY KEY (PATIENT_ID)
);

CREATE OR REPLACE TABLE STAGING.PATIENT_INSURANCE (
    PATIENT_ID            NUMBER(38,0) NOT NULL,
    INSURANCE_PROVIDER_ID NUMBER(38,0) NOT NULL,
    CONSTRAINT PK_PATIENT_INSURANCE PRIMARY KEY (PATIENT_ID, INSURANCE_PROVIDER_ID),
    CONSTRAINT FK_PI_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES STAGING.PATIENTS(PATIENT_ID),
    CONSTRAINT FK_PI_PROVIDER FOREIGN KEY (INSURANCE_PROVIDER_ID) REFERENCES STAGING.INSURANCE_PROVIDERS(INSURANCE_PROVIDER_ID)
);

CREATE OR REPLACE TABLE STAGING.PRESCRIPTIONS (
    PRESCRIPTION_ID NUMBER(38,0) NOT NULL,
    PATIENT_ID      NUMBER(38,0),
    DOCTOR_ID       NUMBER(38,0),
    MEDICATION_ID   NUMBER(38,0),
    QUANTITY        NUMBER(10,0),
    DOSAGE          VARCHAR(100),
    FREQUENCY       VARCHAR(100),
    PRESCRIBED_DATE DATE,
    REFILL_ALLOWED  BOOLEAN,
    REFILL_COUNT    NUMBER(5,0),
    CONSTRAINT PK_PRESCRIPTIONS PRIMARY KEY (PRESCRIPTION_ID),
    CONSTRAINT FK_RX_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES STAGING.PATIENTS(PATIENT_ID),
    CONSTRAINT FK_RX_DOCTOR FOREIGN KEY (DOCTOR_ID) REFERENCES STAGING.DOCTORS(DOCTOR_ID),
    CONSTRAINT FK_RX_MEDICATION FOREIGN KEY (MEDICATION_ID) REFERENCES STAGING.MEDICATIONS(MEDICATION_ID)
);

CREATE OR REPLACE TABLE STAGING.HOSPITAL_VISITS (
    VISIT_ID              NUMBER(38,0) NOT NULL,
    ADMISSION_DATE        DATE,
    DISCHARGE_DATE        DATE,
    PATIENT_ID            NUMBER(38,0),
    DOCTOR_ID              NUMBER(38,0),
    HOSPITAL_ID            NUMBER(38,0),
    INSURANCE_PROVIDER_ID  NUMBER(38,0),
    ROOM_NO                VARCHAR(20),
    ADMISSION_TYPE          VARCHAR(50),
    PROCEDURE_ID             NUMBER(38,0),
    DIAGNOSIS                VARCHAR(500),
    CONSTRAINT PK_HOSPITAL_VISITS PRIMARY KEY (VISIT_ID),
    CONSTRAINT FK_HV_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES STAGING.PATIENTS(PATIENT_ID),
    CONSTRAINT FK_HV_DOCTOR FOREIGN KEY (DOCTOR_ID) REFERENCES STAGING.DOCTORS(DOCTOR_ID),
    CONSTRAINT FK_HV_HOSPITAL FOREIGN KEY (HOSPITAL_ID) REFERENCES STAGING.HOSPITALS(HOSPITAL_ID),
    CONSTRAINT FK_HV_INSURANCE FOREIGN KEY (INSURANCE_PROVIDER_ID) REFERENCES STAGING.INSURANCE_PROVIDERS(INSURANCE_PROVIDER_ID),
    CONSTRAINT FK_HV_PROCEDURE FOREIGN KEY (PROCEDURE_ID) REFERENCES STAGING.PROCEDURES(PROCEDURE_ID)
);

-- ---------------------------------------------------------------------
-- TRANSFORM: RAW -> STAGING
-- Trims whitespace, upper-cases codes, and dedupes on primary key
-- (keeps one row per key using QUALIFY + ROW_NUMBER). Run after RAW
-- is loaded, before ANALYTICS.
-- ---------------------------------------------------------------------

INSERT OVERWRITE INTO STAGING.STATES
SELECT STATE_ID, TRIM(STATE_NAME), UPPER(TRIM(STATE_ABBR))
FROM RAW.STATES
QUALIFY ROW_NUMBER() OVER (PARTITION BY STATE_ID ORDER BY STATE_ID) = 1;

INSERT OVERWRITE INTO STAGING.CITIES
SELECT CITY_ID, TRIM(CITY_NAME), STATE_ID
FROM RAW.CITIES
QUALIFY ROW_NUMBER() OVER (PARTITION BY CITY_ID ORDER BY CITY_ID) = 1;

INSERT OVERWRITE INTO STAGING.ADDRESSES
SELECT ADDRESS_ID, TRIM(STREET_ADDRESS), CITY_ID, TRIM(ZIP)
FROM RAW.ADDRESSES
QUALIFY ROW_NUMBER() OVER (PARTITION BY ADDRESS_ID ORDER BY ADDRESS_ID) = 1;

INSERT OVERWRITE INTO STAGING.HOSPITALS
SELECT HOSPITAL_ID, TRIM(HOSPITAL_NAME), ADDRESS_ID, TRIM(HOSPITAL_PHONE_NO)
FROM RAW.HOSPITALS
QUALIFY ROW_NUMBER() OVER (PARTITION BY HOSPITAL_ID ORDER BY HOSPITAL_ID) = 1;

INSERT OVERWRITE INTO STAGING.DOCTORS
SELECT DOCTOR_ID, TRIM(FIRST_NAME), TRIM(LAST_NAME), HOSPITAL_AFFI, TRIM(SPECIALTY), TRIM(DOC_PHONE_NO)
FROM RAW.DOCTORS
QUALIFY ROW_NUMBER() OVER (PARTITION BY DOCTOR_ID ORDER BY DOCTOR_ID) = 1;

INSERT OVERWRITE INTO STAGING.MEDICATIONS
SELECT MEDICATION_ID, TRIM(MEDICATION_NAME), TRIM(PHARMA_COMPANY), TRIM(CATEGORY), MEDICATION_COST
FROM RAW.MEDICATIONS
QUALIFY ROW_NUMBER() OVER (PARTITION BY MEDICATION_ID ORDER BY MEDICATION_ID) = 1;

INSERT OVERWRITE INTO STAGING.PROCEDURES
SELECT PROCEDURE_ID, TRIM(PROCEDURE_NAME), TRIM(MEDICAL_CATEGORY), PROCEDURE_CHARGE
FROM RAW.PROCEDURES
QUALIFY ROW_NUMBER() OVER (PARTITION BY PROCEDURE_ID ORDER BY PROCEDURE_ID) = 1;

INSERT OVERWRITE INTO STAGING.INSURANCE_PROVIDERS
SELECT INSURANCE_PROVIDER_ID, TRIM(PROVIDER_NAME), TRIM(PLAN_TYPE), TRIM(PHONE_NO)
FROM RAW.INSURANCE_PROVIDERS
QUALIFY ROW_NUMBER() OVER (PARTITION BY INSURANCE_PROVIDER_ID ORDER BY INSURANCE_PROVIDER_ID) = 1;

INSERT OVERWRITE INTO STAGING.PATIENTS
SELECT PATIENT_ID, TRIM(FIRST_NAME), TRIM(LAST_NAME), DOB, UPPER(TRIM(SEX)), UPPER(TRIM(BLOOD_TYPE))
FROM RAW.PATIENTS
QUALIFY ROW_NUMBER() OVER (PARTITION BY PATIENT_ID ORDER BY PATIENT_ID) = 1;

INSERT OVERWRITE INTO STAGING.PATIENT_INSURANCE
SELECT DISTINCT PATIENT_ID, INSURANCE_PROVIDER_ID
FROM RAW.PATIENT_INSURANCE;

INSERT OVERWRITE INTO STAGING.PRESCRIPTIONS
SELECT PRESCRIPTION_ID, PATIENT_ID, DOCTOR_ID, MEDICATION_ID, QUANTITY,
       TRIM(DOSAGE), TRIM(FREQUENCY), PRESCRIBED_DATE, REFILL_ALLOWED, REFILL_COUNT
FROM RAW.PRESCRIPTIONS
QUALIFY ROW_NUMBER() OVER (PARTITION BY PRESCRIPTION_ID ORDER BY PRESCRIPTION_ID) = 1;

INSERT OVERWRITE INTO STAGING.HOSPITAL_VISITS
SELECT VISIT_ID, ADMISSION_DATE, DISCHARGE_DATE, PATIENT_ID, DOCTOR_ID, HOSPITAL_ID,
       INSURANCE_PROVIDER_ID, TRIM(ROOM_NO), TRIM(ADMISSION_TYPE), PROCEDURE_ID, TRIM(DIAGNOSIS)
FROM RAW.HOSPITAL_VISITS
QUALIFY ROW_NUMBER() OVER (PARTITION BY VISIT_ID ORDER BY VISIT_ID) = 1;
